---------------------------------------------------
$ dit -v -d ./ditdir new t1 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new s1/t2 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new g1/s2/t3 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new /t4 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new /s3/t5 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new g2//t6 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new //t7 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new g2/s4/t8 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new g2//t7 -d test
---------------------------------------------------
$ dit -v -d ./ditdir new //t7 -d fail, already exists
Traceback (most recent call last):
  File "/files/Dropbox/dit/venv/bin/dit", line 11, in <module>
    load_entry_point('dit==0.1a0', 'console_scripts', 'dit')()
  File "/files/Dropbox/dit/venv/lib/python3.5/site-packages/dit-0.1a0-py3.5.egg/dit/dit.py", line 687, in main
  File "/files/Dropbox/dit/venv/lib/python3.5/site-packages/dit-0.1a0-py3.5.egg/dit/dit.py", line 656, in interpret
  File "/files/Dropbox/dit/venv/lib/python3.5/site-packages/dit-0.1a0-py3.5.egg/dit/dit.py", line 488, in new
  File "/files/Dropbox/dit/venv/lib/python3.5/site-packages/dit-0.1a0-py3.5.egg/dit/dit.py", line 180, in _create_task
Exception: Already exists: ./ditdir/t7
---------------------------------------------------
$ dit -v -d ./ditdir new t2 -d test
---------------------------------------------------
$ tree ./ditdir
./ditdir
├── g1
│   └── s2
│       └── t3
├── g2
│   ├── s4
│   │   └── t8
│   ├── t6
│   └── t7
├── INDEX
├── s1
│   └── t2
├── s3
│   └── t5
├── t1
├── t2
├── t4
└── t7

6 directories, 11 files
